default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  
  # Either use socket connection (more efficient for local development)
  socket: /opt/homebrew/var/mysql/mysql.sock
  
  # Or use host and port for TCP/IP connection
  # host: localhost
  # port: 3306

development:
  <<: *default
  database: arxiv_visualizer_development

test:
  <<: *default
  database: arxiv_visualizer_test
